org: perrettj4
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: "2"

custom:
  settings:
    DYNAMODB_TABLE: dictionary-table

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: eu-west-1
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.DYNAMODB_TABLE}"

functions:
  list:
    handler: handler.getAllItems
    events:
      - http:
          path: words
          method: get
          cors: true
  create:
    handler: handler.addItem
    events:
      - http:
          path: words
          method: post
          cors: true
  item:
    handler: handler.getItemById
    events:
      - http:
          path: words/{id}
          method: get
          cors: true
  update:
    handler: handler.updateItem
    events:
      - http:
          path: words/{id}
          method: put
          cors: true
  delete:
    handler: handler.deleteItem
    events:
      - http:
          path: words/{id}
          method: delete
          cors: true
resources:
  Resources:
    DynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
